version: '3.8' # https://docs.docker.com/compose/compose-file/compose-versioning/#version-3

services:
  # Web Server acting as proxy (NGINX)    
  webserver:
    image: nginx:alpine
    env_file:
      - webserver/.webserver.env
    volumes:
      - ./webserver/config/etc/nginx/conf.d/default.conf.template.nginx:/etc/nginx/conf.d/default.conf.template.nginx
      - ./webserver/config/etc/ssl:/etc/ssl
      - ./webserver/logs/:/var/log/nginx
      - ../${PROJECT_NAME}_backend:/app
    ports:
      - ${FRONTEND_BACKEND_EXTERNAL_PORT}:80
      - ${BACKEND_FPM_EXTERNAL_PORT}:81
      - ${PHPMYADMIN_EXTERNAL_PORT}:8080
    restart: always
    depends_on:
      - backend
      - frontend
      - phpmyadmin
    container_name: ${PROJECT_NAME}_webserver
    command: /bin/sh -c "envsubst '$$NGINX_HOST $$FRONTEND_CONNECTION_PORT $$BACKEND_CONNECTION_PORT $$BACKEND_FPM_CONNECTION_PORT ' < /etc/nginx/conf.d/default.conf.template.nginx > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - project_network

  # SERVIDOR BASE DE DATOS (Mariadb)
  mariadb:
    image: mariadb:latest
    env_file:
      - mariadb/.mariadb.env
    expose:
      - 3306
    ports:
      - ${MARIADB_EXTERNAL_PORT}:3306
    restart: always
    volumes:
      - ./mariadb/config/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mariadb/data/db/mysql:/var/lib/mysql
      #- ./mariadb/logs/:/var/log/mysql
    container_name: ${PROJECT_NAME}_mariadb
    networks:
      - project_network

  # GESTIÓN BD (phpmyadmin)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_PMADB=phpmyadmin
    user: ${UID}:${UID}
    restart: unless-stopped
    expose:
      - 80
    depends_on:
      - mariadb
    links:
      - mariadb:db
    container_name: ${PROJECT_NAME}_phpmyadmin
    networks:
      - project_network

  # CONTENEDOR DEL BACKEND (API REST CON LARAVEL)
  backend:
    env_file:
      - backend/.backend.env
    build:
      context: backend
      args:
        user: ${USER}
        uid: ${UID}
    image: jraicr/php-xdebug-composer:fpm-alpine
    working_dir: /app
    entrypoint: /docker-entrypoint.sh
    expose:
      - ${BACKEND_EXPOSE_PORT}
      - ${BACKEND_FPM_EXPOSE_PORT}
    depends_on:
      - mariadb
    restart: always
    volumes:
      - ../${PROJECT_NAME}_backend:/app # Laravel Project
      - ./backend/config/etc/php/conf.d/php.ini-development.ini:/usr/local/etc/php/php.ini # PHP Config
      - ./backend/config/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf # PHP-FPM Config
      - ./backend/config/etc/php-fpm.d/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf # PHP-FPM Config
      - ./backend/config/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini # PHP XDebug Config
      - ./backend/config/etc/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini # PHP OPcache config
      - ./backend/docker-entrypoint.sh:/docker-entrypoint.sh # Backend Docker entrypoint script
    container_name: ${PROJECT_NAME}_backend
    networks:
      - project_network

  # CONTENEDOR DEL FRONT END (VUE+VITE)
  frontend:
    env_file:
      - frontend/.frontend.env
    build:
      context: frontend
    image: jraicr/node-envsubst:current-alpine
    user: ${UID}:${UID}
    working_dir: /home/node/app
    expose:
      - ${FRONTEND_EXPOSE_PORT}
    volumes:
      - ../${PROJECT_NAME}_frontend:/home/node/app
      - ./frontend/config/vite.config.template.js:/home/node/app/vite.config.template.js
    environment:
      NODE_ENV: ${NODE_DEVELOPMENT}
    command: /bin/sh -c "envsubst '$$FRONTEND_INTERNAL_PORT $$FRONTEND_EXTERNAL_PORT' < /home/node/app/vite.config.template.js > /home/node/app/vite.config.js && npm run dev -- --port ${FRONTEND_EXPOSE_PORT}"
    container_name: ${PROJECT_NAME}_frontend
    networks:
      - project_network

networks:
  project_network:
    name: ${PROJECT_NAME}_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/16"
          gateway: "172.25.0.1"
